- config.yaml
- controllers/namespace_controller.go
- controllers/namespace_controller_test.go
- pkg/config/types.go
ref: https://github.com/cybozu-go/accurate/issues/2
> Allow shell glob patters for label/annotation keys.

- cmd/kubectl-accurate/sub/sub.go
- cmd/kubectl-accurate/sub/sub_list.go
- cmd/kubectl-accurate/sub/template.go
- cmd/kubectl-accurate/sub/template_list.go
- docs/info.md
- docs/kubectl-accurate.md
- e2e/e2e_test.go
ref: https://github.com/cybozu-go/accurate/issues/3
> Add kubectl-accurate template list sub command.

- .dockerignore
- .github/workflows/release.yaml
- .gitignore
- .goreleaser.yaml
- .krew.yaml
- Makefile
- docs/install-plugin.md
refs: https://github.com/cybozu-go/accurate/issues/24
Release kubectl-accurate plugin to krew-index.
* Build the binary to be released using [goreleaser](https://github.com/goreleaser/goreleaser) and archive it as `.tar.gz`
* krew plugins must be packaged as .zip or .tar.gz archives
* https://krew.sigs.k8s.io/docs/developer-guide/plugin-manifest/#specifying-plugin-download-options
* Use krew-release-bot to update krew-index
* https://krew.sigs.k8s.io/docs/developer-guide/release/automating-updates/
* Add tar.gz archive to v0.1.0 release
* This will be done manually
* `GORELEASER_CURRENT_TAG=v0.1.0 goreleaser release --skip-publish --skip-announce --skip-validate --rm-dist`
* Send a Pull Request to https://github.com/kubernetes-sigs/krew-index
I've tested it in my own repository that I …
> Support krew release

- cmd/accurate-controller/sub/root.go
- cmd/accurate-controller/sub/run.go
- docs/accurate-controller.md
to match the limit of HNC.
https://github.com/kubernetes-sigs/multi-tenancy/issues/369
> Adjust QPS for querying kube-apiserver to 50

- Makefile
- charts/accurate/crds/accurate.cybozu.com_subnamespaces.yaml
- charts/accurate/templates/generated/generated.yaml
- e2e/Makefile
kustomize 4.0.5 or later has a issue with long lines being broken.
https://github.com/kubernetes-sigs/kustomize/issues/3969
This will cause `helm install` to fail.
Signed-off-by: zoetrope <a.ikezoe@gmail.com>
> Fix the broken chart

- docs/concepts.md
- docs/subnamespaces.md
The manual states that Accurate propagates labels/annotations, however (although it makes sense) it is not plainly obvious that Accurate only propagates labels/annotations that have been configured in that matter via config.yaml.
This PR adds some minor clarifications in the manual to prevent such misunderstandings
> docs: clarify the behavior of label/annotation propagation

- charts/accurate/templates/certificate.yaml
- config/certmanager/certificate.yaml
We are using cert-manager/approver-policy in our clusters, and are hitting this issue: https://github.com/cert-manager/approver-policy/issues/179
This PR adds the `cert-manager.io` as the issuer group - which is anyway the default in cert-manager controller.
> fix: add missing spec.issuerRef.group to cert-manager Certificate|

- .github/workflows/ci.yaml
- aqua.yaml
- e2e/Makefile
When reading through the project docs, I noticed https://cybozu-go.github.io/accurate/maintenance.html#how-to-update-supported-kubernetes. I already did the last step in https://github.com/cybozu-go/accurate/pull/88, so this PR is to finalize the upgrade to K8s 1.28 as documented.
> build(deps): finalize bump to Kubernetes 1.28

- cmd/accurate-controller/sub/root.go
- controllers/propagate.go
- go.mod
- go.sum
- pkg/config/feature_gate.go
- pkg/feature/feature.go
This adds a temporary/experimental feature gate that allows a user to disable the [Annotating a resource to propagate resources created from it](https://cybozu-go.github.io/accurate/propagation.html#annotating-a-resource-to-propagate-resources-created-from-it) feature. As the Accurate controller works at present, we need a way to prevent Accurate from touching resources in namespaces that are not and never will be, managed by Accurate.
The idea is to deprecate and eventually remove this new feature gate when the root cause is fixed.
Relates to https://github.com/cybozu-go/accurate/issues/87 (workaround)
````
$ bin/accurate-controller --help
accurate controller
Usage:
accurate-controller [flags]
Flags:
--add_dir_header                    If true, adds the file directory to the header of …
```
> feat: add DisablePropagateGenerated feature gate

- .gitattributes
This PR is a simple improvement to the review process by using the feature described here: https://docs.github.com/en/repositories/working-with-files/managing-files/customizing-how-changed-files-appear-on-github
With this merged it will be a lot simpler to review PRs affecting generated files, as the marked as generated files will be collapsed by default in the PR diff-view. Example: https://github.com/cybozu-go/accurate/pull/96 will be easier to review and comment on.
> chore: mark generated files in .gitattributes

- charts/accurate/templates/deployment.yaml
In https://github.com/cybozu-go/accurate/pull/99 I discovered that the `config.extraArgs` Helm value is not treated as a list when rendering the Deployment template - which makes it harder to use more than one extra argument to the workload. This PR fixes this.
> fix(helm): controller.extraArgs should be treated as list

- README.md
- controllers/propagate.go
- controllers/propagate_test.go
- docs/annotations.md
- docs/concepts.md
- docs/design.md
- docs/overview.md
- docs/propagation.md
- docs/reconcile.md
- pkg/constants/meta.go
As agreed in https://github.com/cybozu-go/accurate/issues/87#issuecomment-1760038161 we think it's time to initiate the removal of the propagate-generated feature. This PR does:
- update docs to inform about the deprecated feature
-  mark affected code as deprecated
Relates to https://github.com/cybozu-go/accurate/issues/87
Close https://github.com/cybozu-go/accurate/issues/93
> docs: deprecate propagate-generated feature

- controllers/suite_test.go
- docs/config.md
- e2e/values.yaml
- pkg/feature/feature.go
As agreed in https://github.com/cybozu-go/accurate/issues/87#issuecomment-1760038161, this graduates the `DisablePropagateGenerated ``to Beta and enables it by default. This does not fix https://github.com/cybozu-go/accurate/issues/87, but I still think we can close the issue as "not a problem" - since the problematic feature is no longer enabled by default.
Should probably be merged/released after https://github.com/cybozu-go/accurate/pull/95. This PR is quite easy to rebase, so it can just stay open until we are ready for these changes.
Close https://github.com/cybozu-go/accurate/issues/87
PS: The structure/wording of the new feature gates doc paragraph is almost a copy of https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/. Kudos to Kubernetes documentation …
> chore: enable DisablePropagateGenerated feature gate by default

- api/accurate/v1/subnamespace_conversion.go
- api/accurate/v2alpha1/subnamespace_types.go
- charts/accurate/templates/generated/crds.yaml
- cmd/accurate-controller/sub/run.go
- cmd/kubectl-accurate/sub/util.go
- config/crd/bases/accurate.cybozu.com_subnamespaces.yaml
- config/crd/kustomization.yaml
- config/crd/kustomizeconfig.yaml
- config/crd/patches/cainjection_in_subnamespaces.yaml
- config/crd/patches/webhook_in_subnamespaces.yaml
- config/kustomize-to-helm/overlays/crds/crd_conversion_patch.yaml
- config/kustomize-to-helm/overlays/crds/kustomization.yaml
- controllers/suite_test.go
- e2e/e2e_test.go
- hooks/subnamespace.go
- hooks/suite_test.go
This PR makes the new v2alpha1 version of the API served and enables the conversion webhook using logic established in https://github.com/cybozu-go/accurate/pull/96.
After this, I will suggest changing the SubNamespace controller to watch/reconcile version v1alpha1 (using SSA). When the controller watches v2alpha1 version, I think it also makes sense to switch the stored version.
> feat: enable v2alpha1 API with conversion webhook

- Makefile
- charts/accurate/templates/generated/generated.yaml
- config/webhook/manifests.yaml
- go.mod
- hooks/subnamespace.go
- hooks/subnamespace_test.go
- hooks/subnamespace_v2_test.go
- hooks/suite_test.go
First I want to clarify that this PR does not fix any problem. 😉 I just felt uncertain if the webhooks were addressing the new (and now served) `SubNamespace` API version. But they do - since the default `matchPolicy` in webhooks is `Equivalent`. Since I already made an effort to check this with tests, I think my changes could be added as an improvement to the hooks tests. It is probably unlikely, but if we want to test webhooks for different behavior between versions, this is possible now. 
Also configured `matchPolicy` explicitly in webhook configuration resources, which I think makes sense now, as we have to ensure the webhooks address all versions.
> chore: ensure webhooks are handling all API versions

- controllers/propagate_test.go
- pkg/constants/meta.go
This fixes a leftover after https://github.com/cybozu-go/accurate/pull/95. Somehow we forgot to deprecate the user-facing annotation for the now deprecated propagate-generated feature.
> chore: deprecate user-facing propagate-generated annotation

- controllers/namespace_controller_test.go
- controllers/propagate_test.go
- controllers/subnamespace_controller_test.go
- controllers/suite_test.go
- hooks/namespace_test.go
- hooks/subnamespace_test.go
- hooks/subnamespace_v2_test.go
This introduces [komega](https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.16.3/pkg/envtest/komega) from controller-runtime envtest framework. IMO it makes the test more readable and test-code shorter. Also standardizing on the Ginkgo pattern to use `Expect(<func>).Should(Succeed())` when the K8s client operation is supposed to success without error. It just makes things a bit more compact.
I hope you like this, and that the PR is reviewable. It is a bit large in the number of changes, but I have attempted to change things in a way that doesn't clutter the diff.
This PR is mainly motivated by planned test improvements in https://github.com/cybozu-go/accurate/pull/112.
> test: migrate envtests to komega

- .github/workflows/ci.yaml
- aqua.yaml
- e2e/Makefile
This bumps the supported Kubernetes to 1.29 as documented in https://cybozu-go.github.io/accurate/maintenance.html. The Go dependencies are bumped in https://github.com/cybozu-go/accurate/pull/117.
It seems like Renovate is no longer operating on this project, so I bumped the patch versions of the supported K8s releases also.
> build(deps): bump Kubernetes to 1.29

- controllers/namespace_controller.go
- controllers/namespace_controller_test.go
- controllers/propagate.go
- controllers/ssa_client.go
- controllers/subnamespace_controller.go
- docs/subnamespaces.md
This PR migrates all updates in controllers to server-side apply (SSA), except the update removing the finalizer on SubNamespace - which is changed to a standard patch.
SSA works a bit differently than updates, so some of the optimizations had to go in this PR. I am hoping this change won't increase the load on the api-server significantly, but it's something we should monitor. I have added stable resource version tests for namespaces - which are now SSAed unconditionally.
Namespace controller tests are currently highly scenario-based, which makes them long and hard to read/modify. I have added some additional assertions of modified behavior on migration to SSA, but I suggest refactoring the tests in a follow-up PR to improve the test coverage. I can prepare a PR if you agree.
Fixes #98
> chore: migrate controllers to SSA

- hooks/namespace_test.go
While working on https://github.com/cybozu-go/accurate/pull/121 I noticed some flaky tests I have seen before in previous pull requests. Flakes are annoying, so this PR attempts to improve this somehow.
Since the webhook uses a caching client, the webhook might deny the request based on a non-updated cache. If the test creates a namespace referring to another namespace just created, this can make the test fail. Hopefully, this PR will improve the situation by replacing `Except` with `Eventually` in such cases.
I have also added assertions of error messages expected from the webhook for denied requests. This should prevent tests from passing if the request fails for any other reason than the expected. This will force us to update the test if error messages are changed, but I think this …
> test: improve namespace webhook tests

- controllers/namespace_controller.go
- controllers/namespace_controller_test.go
- controllers/propagate.go
- controllers/ssa_client.go
- controllers/subnamespace_controller.go
- controllers/suite_test.go
This PR reuses the upstream code that `kubectl` uses to upgrade `managedFields` from CSA to SSA. It appears like subresources are not supported yet, but I am working on it in https://github.com/kubernetes/kubernetes/pull/123484. The PR allowing us to upgrade managed fields for subresources is now merged and should be released with the upcoming K8s 1.30. I will create a follow-up PR when the improved helper is available, but this PR fixes the main issue.
Fixes https://github.com/cybozu-go/accurate/issues/120
> fix: upgrade managed fields in controller resources from CSA to SSA

- controllers/ssa_client.go
- controllers/subnamespace_controller.go
This PR fixes the leftovers from https://github.com/cybozu-go/accurate/pull/121 and completes the operator migration from CSA to SSA. We should at some point remove the CSA to SSA upgrade code - as noted in the migration TODOs.
Would it be possible to cut a new release soon?
> fix: upgrade SubNamespace status managed fields from CSA to SSA

- cmd/accurate-controller/sub/run.go
We are using JSON log format in our installation of Accurate. Here is an example log:
````
{"level":"info","ts":"2024-05-21T12:28:14Z","logger":"controller-runtime.builder","msg":"skip registering a mutating webhook, object does not implement admission.Defaulter or WithDefaulter wasn't called","GVK":"accurate.cybozu.com/v1, Kind=SubNamespace"}
{"level":"info","ts":"2024-05-21T12:28:14Z","logger":"controller-runtime.builder","msg":"skip registering a validating webhook, object does not implement admission.Validator or WithValidator wasn't called","GVK":"accurate.cybozu.com/v1, Kind=SubNamespace"}
{"level":"info","ts":"2024-05-21T12:28:14Z","logger":"controller-runtime.webhook","msg":"Registering webhook","path":"/convert"}
{"level":"info","ts":"2024-05-21T12:28:14Z","logger":"controller-run …
```
> fix: set default klog logger to avoid breaking log format

- api/accurate/v2/subnamespace_types.go
- api/accurate/v2alpha1/subnamespace_types.go
- charts/accurate/templates/generated/crds.yaml
- config/crd/bases/accurate.cybozu.com_subnamespaces.yaml
- controllers/namespace_controller.go
- controllers/namespace_controller_test.go
- controllers/ssa_client.go
- controllers/subnamespace_controller.go
- controllers/subnamespace_controller_test.go
- controllers/suite_test.go
This PR changes the stored version from v2alpha1 to v2, ref. https://github.com/cybozu-go/accurate/pull/132. Also changing the controller to use the new stored version to avoid an excessive number of conversions.
> chore: change stored version of API to v2

- charts/accurate/MIGRATION.md
- charts/accurate/values.yaml
- cmd/accurate-controller/sub/run.go
- docs/config.md
- e2e/values.yaml
- pkg/config/suite_test.go
- pkg/config/types.go
- pkg/config/types_test.go
This PR adds more validation of configuration on startup. The operator must have cluster-wide RBAC to CRUD all configured watches to function as intended by the user. At startup, we will now use [SelfSubjectAccessReview](https://kubernetes.io/docs/reference/kubernetes-api/authorization-resources/self-subject-access-review-v1/) to check the required RBAC for all configured watches and crash if anything is missing.
Note: After migrating to SSA, we no longer need the `update` verb. I included this minor change in this PR, but please let me know if a dedicated PR is required.
Close https://github.com/cybozu-go/accurate/issues/102
> fix: check RBAC to watched resources on startup

- e2e/e2e_test.go
- hooks/subnamespace_deprecated_test.go
- hooks/subnamespace_test.go
After start serving v2 API it makes sense to migrate tests to this new version. Older API versions will hopefully be deprecated by merging https://github.com/cybozu-go/accurate/pull/128.
After this PR, we have little use of older API versions internal. @zoetrope, maybe you can migrate the kubectl plugin to use v2 API?
> test: migrate tests to v2 API

- api/accurate/v1/subnamespace_types.go
- api/accurate/v2alpha1/subnamespace_types.go
- charts/accurate/templates/generated/crds.yaml
- config/crd/bases/accurate.cybozu.com_subnamespaces.yaml
- docs/crd_subnamespace.md
The v2alpha1 version of the SubNamespace API has been available for a while, and I think it's time to consider deprecating the v1 version. The newer version has a much better observed state UX with conditions. We should probably make v2 (or v2beta1) available - to not "scare" our users from migrating (to an alpha version).
> chore: deprecate v1 and v2alpha1 SubNamespace API

- Makefile
- charts/accurate/README.md
- charts/accurate/templates/NOTES.txt
- charts/accurate/templates/_helpers.tpl
- charts/accurate/templates/generated/crds.yaml
- charts/accurate/values.yaml
- config/crd-only/crd_conversion_patch.yaml
- config/crd-only/kustomization.yaml
- config/kustomize-to-helm/overlays/crds/crd_resource_policy_patch.yaml
- config/kustomize-to-helm/overlays/crds/kustomization.yaml
The purpose of this PR is twofold: fix the currently broken CRDs standalone install (https://github.com/cybozu-go/accurate/issues/139) and improve the Helm CRDs install by adding `helm.sh/resource-policy: keep` annotation (by default) to CRDs to prevent Helm from uninstalling the CRD when the Helm release is uninstalled. The general improvement of Helm CRD install will hopefully allow more users to let Helm manage CRDs.
I will suggest publishing CRDs as a release artifact to avoid the new `crd-only` kustomize overlay. As long as we have conversion webhooks, installing CRDs separately will be somehow borked.
The solution is heavily inspired by recent work in cert-manager!
Fixes https://github.com/cybozu-go/accurate/issues/139
> fix: improve CRD install (Helm and standalone)

- charts/accurate/templates/configmap.yaml
This corrects a bug in https://github.com/cybozu-go/accurate/pull/142. Without this fix, the Helm chart rendering is erroring out with:
````
Error: Error: template: accurate/templates/deployment.yaml:18:28: executing "accurate/templates/deployment.yaml" at <include (print $.Template.BasePath "/configmap.yaml") .>: error calling include: template: accurate/templates/configmap.yaml:24:20: executing "accurate/templates/configmap.yaml" at <.Values.controller.config.propagateLabelKeyExcludes>: can't evaluate field Values in type []interface {}
````
Sorry for this, but this is a blocking error that will require a new patch release (of the Helm chart, at least).
CC @zoetrope @ymmt2005
> fix(helm): correct invalid ConfigMap template

- charts/accurate/templates/generated/generated.yaml
- config/webhook/manifests.yaml
- hooks/subnamespace.go
- hooks/subnamespace_test.go
If a client is allowed to delete a `SubNamespace` where the sub-namespace has child namespaces, the controller becomes stuck on the finalization of the `SubNamespace`. The controller will not be allowed to delete the sub-namespaces by our namespace webhook.
Since Kubernetes has no way to undelete a resource (unset the `deletionTimestamp` field), all child namespaces must be manually deleted to allow the `SubNamespace` deletion to be finalized.
This PR introduces handling of DELETE verb to the subnamespaces validating webhook ensuring no subnamespaces can be deleted if the sub-namespace has child namespaces. It seems like there was a minor bug in the validating webhook configuration: it was configured to handle UPDATE verb, but the implementation was only addressing CREATE.
Close …
> fix(webhook): deny deletion of SubNamespace with child namespaces

- charts/accurate/templates/generated/generated.yaml
- cmd/kubectl-accurate/sub/sub_create.go
- cmd/kubectl-accurate/sub/sub_cut.go
- cmd/kubectl-accurate/sub/sub_delete.go
- cmd/kubectl-accurate/sub/sub_graft.go
- cmd/kubectl-accurate/sub/sub_move.go
- config/webhook/manifests.yaml
- e2e/e2e_test.go
- hooks/subnamespace.go
This PR removes all usage of deprecated APIs/types that can be done before we remove the deprecated APIs.
> chore: remove use of deprecated APIs

- cmd/accurate-controller/sub/run.go
- controllers/subnamespace_controller.go
- controllers/subnamespace_controller_test.go
- e2e/e2e_test.go
- e2e/testdata/conflicting-subnamespace.yaml
- pkg/constants/indexer.go
- pkg/indexing/indexing.go
Our tenants use GitOps to provision sub-namespaces, and not `kubectl-accurate`. We run on OpenShift, and OpenShift has a feature allowing users in the `self-provisioner` cluster role to create namespaces by issuing a ProjectRequest create request.   We want to migrate to Accurate, but will still have to support the OpenShift mechanism for a long time.
Recently we've had users pre-creating an OpenShift Project before provisioning the _SubNamespace_ resource that is supposed to control the desired namespace. This will not work, making the subnamespace enter a conflicting state right after creation by the tenant GitOps. The user observes this problem by inspecting the _SubNamespace_ status and other GitOps failures caused by missing RBAC in the target namespace.
The natural thing to do when …
> fix: should resolve SubNamespace conflict when sub-namespace deleted

- .github/workflows/ci.yaml
- .github/workflows/mdbook.yaml
upload-artifact and download-artifact were deprecated by 2024/11/30.
https://github.com/actions/download-artifact
> Update upload-artifact and download-artifact

- Makefile
- cmd/kubectl-accurate/sub/list.go
- cmd/kubectl-accurate/sub/template_list.go
- Resolved the N+1 problem by optimizing namespace retrieval for faster searches.
- Fixed tree display indentation using tree symbols.
- Optimized namespace hierarchy retrieval to eliminate redundant queries.
- Improved tree view formatting by using tree symbols and removing unnecessary indent variables.
- Sorted namespaces in ascending alphabetical order.
- The current implementation suffers from an N+1 problem when searching namespaces, leading to poor performance.
- This update improves user experience by significantly speeding up namespace lookups.
> Fix N+1 Issue in Namespace Search and Enhance Tree View

- .github/workflows/helm.yaml
- .github/workflows/release.yaml
- Dockerfile
As per https://github.com/cybozu-go/accurate/issues/155 , this makes the CI build a multi-arch image.
The image is built using `buildx`, as per https://docs.docker.com/build/building/multi-platform/#prerequisites - Custom Builder .
On the dockerfile side, I've done it by using Go's cross-compilation abilities. The build stage is always host-native, and the binary is cross-compiled where necessary. This is the fastest way of doing things and works well for pure Go projects like this.
On the CI side, the Helm check needed to change a little bit: docker's local store can't handle multi-arch images, so instead of building to the local store and then using `kind load docker-image`, we set up a kind registry and push straight into that instead.
In addition, I've set the image to compress with …
> Build multiarch image
